project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "data/"
    - "files/"
    - "scripts/"

website:
  title: "EPsy 8264"
  navbar:
    background: "#0F2E3D"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - sidebar:assignments
      - text: "Data"
        file: data.qmd
      - text: "Instructor"
        file: about.qmd
        
  sidebar:
    - id: assignments
      title: "Assignments"
      style: "docked"
      background: light
      collapse-level: 1
      contents: 
        - assignments.qmd
        - assignments/assignment-01.qmd
        - assignments/assignment-02.qmd
        - assignments/assignment-03.qmd

format:
  html:
    theme: cosmo
    css: ["assets/style.css"]
    toc: true
    header-includes: |
      <script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>
    sidebar: false


  
