---
title: "Calendar"
---


The calendar below lists the tentative course topics. The dates listed are subject to change at the instructor's discretion.

<br /><br />


<table class="table">

<thead>
<tr>
<th style="width:5%;text-align:center"></th>
<th style="width:10%;">Date</th>
<th style="width:10%;text-align:center">Reading</th>
<th style="width:65%;">Topic</th>
<th style="width:10%;text-align:center">Notes</th>
</tr>
</thead>



<tbody>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 06</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/01-welcome-to-8264.html"><span class="fa fa-book"></span></a>
</td>
<td>Welcome to EPsy 8264</td>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
</tr>


<!-- Unit 01: MATHEMATICAL AND COMPUTATIONAL FOUNDATIONS -->

<tr>
<td colspan="5"><b>Unit 01: Mathematical and Computational Foundations</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 08</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/02-introduction-to-matrix-algebra.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Introduction to Matrix Algebra</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="worksheets/02-introduction-to-matrix-algebra.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 13</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 15</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/03-ols.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">OLS Regression using Matrices and its Properties</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/03-ols-regression.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 20</td>
</tr>


<!-- Unit 02: SIMULATION -->


<tr>
<td colspan="5"><b>Unit 02: Simulation</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 22</td>
<td align="center" style="vertical-align:middle;" rowspan="3">
  <a class="my-link" href="readings/04-simulating-from-the-regression-model.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="3">Simulating from the Regression Model</td>
<td align="center" style="vertical-align:middle;" rowspan="3">
  <a class = "my-link" href="notes/04-simulating-from-the-regression-model.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 27</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 29</td>
</tr>


<!-- Unit 03: REGRESSION DIAGNOSTICS -->


<!-- <tr> -->
<td colspan="5"><b>Unit 03: Regression Diagnostics</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 04</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/05-regression-diagnostics.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Regression Diagnostics</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/05-regression-diagnostics.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 06</td>
</tr>


   

<!-- Unit 03: HETEROSKEDASTICITY-->

<tr>
<td colspan="5"><b>Unit 04: Tools for Dealing with Heteroskedasticity</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 11</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/06-variance-stabilizing-transformations.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Variance Stabilizing Transformations</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/06-tools-for-dealing-with-heteroskedasticity.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 13</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/07-wls-and-sandwich-estimation.html
  "><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Weighted Least Squares (WLS) and Sandwich Estimation</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/06-tools-for-dealing-with-heteroskedasticity.html"><span class="fas fa-link"></span></a>
</td>
</tr>


Unit 04: COLLINEARITY


<tr>
<td colspan="5"><b>Unit 05: Diagnosing Collinearity and Tools for Dealing with It</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 18</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/08-diagnosing-collinearity.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Diagnosing Collinearity</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/07-diagnosing-collinearity.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 20</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 25</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/09-pca-via-spectral-decomposition.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Principal Components Analysis via Spectral Decomposition</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/08-pca-via-spectral-decomposition.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 27</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 01</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/10-pca-via-svd.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Principal Components Analysis via Singular Value Decomposition</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/09-pca-via-svd.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Oct. 27</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <!-- <a class="my-link" href="readings/10-pca-via-svd.html"><span class="fa fa-book"></span></a> --> -->
<!-- </td> -->
<!-- <td style="vertical-align:middle;">Principal Components on Different Input Matrices</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <!-- <a class = "my-link" href="notes/08-pca-via-svd.html"><span class="fas fa-link"></span></a> --> -->
<!-- </td> -->
<!-- </tr> -->



<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 03</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/11-biased-estimation-ridge-regression.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Biased Estimation: Ridge Regression</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/10-biased-estimation-ridge-regression.html"><span class="fas fa-link"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 08</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS&mdash;Mental Health Break/Andy at a Conference</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 10</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/11-biased-estimation-ridge-regression.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Biased Estimation: Ridge Regression</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/10-biased-estimation-ridge-regression.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<!-- Unit 05: MODEL SELECTION -->


<!-- <tr> -->
<!-- <td colspan="5"><b>Unit 05: Model Selection</b></td> -->
<!-- </tr> -->

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Nov. 15</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td style="vertical-align:middle;">Model Selection Activity</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class = "my-link" href="worksheets/13-model-selection.html"><span class="fas fa-link"></span></a> -->
<!-- </td> -->
<!-- </tr> -->


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Nov. 17</td> -->
<!-- <td align="center" style="vertical-align:middle;" rowspan="2"> -->
<!--   <a class="my-link" href="readings/12-model-selection.html"><span class="fa fa-book"></span></a> -->
<!-- </td> -->
<!-- <td style="vertical-align:middle;" rowspan="2">Model Selection: The 'Vintage' Methods</td> -->
<!-- <td align="center" style="vertical-align:middle;" rowspan="2"> -->
<!--   <a class = "my-link" href="handouts/2021-10-26-notes-model-selection.pdf"><span class="fas fa-link"></span></a> -->
<!-- </td> -->
<!-- </tr> -->

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Nov. 22</td> -->
<!-- </tr> -->


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;" rowspan="2">&nbsp;</td> -->
<!-- <td>Nov. 29</td> -->
<!-- <td align="center" style="vertical-align:middle;" rowspan="2"> -->
<!--   <a class="my-link" href="readings/13-cross-validation.html"><span class="fa fa-book"></span></a> -->
<!-- </td> -->
<!-- <td style="vertical-align:middle;" rowspan="2">Model Selection: Cross-Validation Methods</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class = "my-link" href="posts/2021-11-18-notes-cross-validation"><span class="fas fa-link"></span></a> -->
<!-- </td> -->
<!-- </tr> -->

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Dec. 01</td> -->
<!-- </tr> -->



<!-- Unit 06:PATH ANALYSIS -->

<!-- <tr> -->
<!-- <td colspan="5"><b>Unit 06: Path Analysis</b></td> -->
<!-- </tr> -->

<!-- CUT THIS: Add to READING  -->


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Dec. 01</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class="my-link" href="readings/14-regression-from-summary-measures.html"><span class="fa fa-book"></span></a> -->
<!-- </td> -->
<!-- <td style="vertical-align:middle;">Regression from Summary Measures</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class = "my-link" href="posts/2021-11-22-notes-regression-from-summary-measures"><span class="fas fa-link"></span></a> -->
<!-- </td> -->
<!-- </tr> -->



<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Dec. 06</td> -->
<!-- <td align="center" style="vertical-align:middle;" rowspan="2"></td> -->
<!-- <td style="vertical-align:middle;" rowspan="2">Path Analysis</td> -->
<!-- <td align="center" style="vertical-align:middle;" rowspan="2"> -->
<!--   <a class = "my-link" href="posts/2021-12-08-notes-path-models"><span class="fas fa-link"></span></a> -->
<!-- </td> -->
<!-- </tr> -->

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Dec. 08</td> -->
<!-- </tr> -->

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Dec. 13</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td style="vertical-align:middle;">NO CLASS</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- </tr> -->

</tbody>
</table>






